config/routes.rb
Rails.application.routes.draw do
  resources :prices
  scope :api do
    resources :prices do
      resources :products, only: :index
    end
    resource :order, only: :create
  end

  root 'prices#index'
  get '*anything' => 'prices#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :price
  after_create :send_email

  private
  def send_email
    OrderCreated.delay.notification id
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  mount_uploader :file, PriceUploader
  has_many :products, dependent: :destroy
  validates_presence_of :file
  after_commit :process, if: ->(p){p.previous_changes.include? :file}

  state_machine :state, initial: :created do
    event(:processing_started) {transition :created => :processing}
    event(:processing_finished) {transition :processing => :processed}
    event(:processing_failed) {transition any => :failed}
  end

  def name
    Pathname.new(file.path).basename
  end

  def process
    XLSParser.perform_async(id)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :price
  validates_presence_of :name
  validates_presence_of :category
  validates_presence_of :code
  validate :prices_presence

  %i[retail_price wholesale dealer_price partner_price].each_with_index do |name, i|
    define_method("#{name}=") do |price|
      self[:prices] ||= []
      prices[i]=(price*100).to_i rescue nil
      prices_will_change!
    end
  end

  def prices_presence
    prices.count == 4 and prices.all?{|p| p.to_i > 0}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  respond_to :json, only: :create
  def create
    order = Order.new order_params
    if order.save
      render json: {message: 'Заказ отправлен'}, status: 201
    else
      render json: order.errors, status: 422
    end
  end

  private
  def order_params
    params.require(:order).permit(:price_id, product_ids: [])
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  def index
    @prices = Price.order(:created_at).all
  end

  # GET /prices/1
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  def create
    @price = Price.new(price_params)

    if @price.save
      redirect_to prices_path, notice: 'Price was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /prices/1
  def update
    if @price.update(price_params)
      redirect_to @price, notice: 'Price was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /prices/1
  def destroy
    @price.destroy
    redirect_to prices_url, notice: 'Price was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def price_params
      params.require(:price).permit(:file) if params[:price]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/prices_helper.rb
module PricesHelper
  def state_icon(price)
    case price.state
    when "created"    then content_tag :span, nil, class: 'glyphicon glyphicon-floppy-open'
    when "processing" then content_tag :progress, nil
    when "processed"  then content_tag :span, nil, class: 'glyphicon glyphicon-check'
    else 
      price.state
    end
  end
end

app/views/order_created/notification.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8" content='text/html; charset=UTF-8' http-equiv='Content-Type')
  %body
    %html
      %table
        %thead
          %tr
            %th name
            %th count
            %th price

        %tbody
          - sum = 0
          - @products.each do |p|
            -count = @order.product_ids.count p.id
            -price = p.prices[0]
            %tr
              %td= p.name
              %td= count
              %td
                $
                = 0.01*price
              - sum+= count*price
      %p
        Сумма: $
        = 0.01 * sum

app/views/prices/_form.html.haml
= bootstrap_form_for @price, inline_errors: false do |f|
  = f.errors_on :file
  = f.file_field :file, wrapper_class: 'btn-file btn color2a', label: 'Select file', onchange: 'javascript:this.form.submit();'

app/views/prices/edit.html.haml
%h1 Reupload price

.col-xs-2
  = render 'form'
.col-xs-2
  = link_to 'Cancel', :back, class: 'btn'

app/views/prices/index.html.haml
%h1 Listing prices

%table.table.table-striped.table-bordered.color2#prices
  %thead
    %tr
      %th name
      %th uploaded
      %th state
      %th products
      %th
  %tbody
    - @prices.each do |price|
      %tr{class: [price.state, :price], id: "price_#{price.id}"}
        %td= link_to price.name, price
        %td
          = time_ago_in_words price.created_at
          ago
        %td= state_icon price
        %td= link_to price.products.count, price, class: :badge
        %td
          .btn-group.btn-group-xs
            = link_to edit_price_path(price), class: :btn do
              %span.glyphicon.glyphicon-sort
            = link_to price, :method => :delete, class: 'btn btn-inverse', :data => { :confirm => 'Are you sure?' } do
              %span.text-danger.glyphicon.glyphicon-fire

= link_to new_price_path, class: :btn do
  New Price
  %span.glyphicon.glyphicon-log-in

app/views/prices/new.html.haml
%h1 Upload price

.col-xs-2
  = render 'form'
.col-xs-2
  = link_to 'Cancel', :back, class: 'btn'

app/views/prices/show.html.haml
= javascript_tag "products=" + @price.products.to_json
%p
  %h1
    = @price.name
    .small
      uploaded
      = distance_of_time_in_words_to_now @price.updated_at
      ago
%table.table.table-striped.table-bordered.color2#price
  %thead
    %tr
      %th name
      %th action
      %th p1
      %th p2
      %th p3
      %th p3
  %tbody
    - @price.products.each do |product|
      %tr{id: "product_#{product.id}"}
        %td= product.name
        %td
          %a.btn.btn-xs.color2c.cart
            %span.glyphicon.glyphicon-shopping-cart
        - product.prices.each do |price|
          %td= number_to_currency(0.01*price, precision: 2) if price

%p
  = link_to prices_path, class: :btn do
    %span.glyphicon.glyphicon-arrow-left
  
  = link_to @price.file_url, class: :btn do
    %span.glyphicon.glyphicon-download-alt
    = @price.file.file.extension

#cart.panel.panel-default.col-xs-2